version: "3.9"
services:
  api:
    build:
      context: .
      target: dev
    container_name: echo_api
    env_file: .env
    restart: always
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.0
    container_name: echo_db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:${DB_PORT}

volumes:
  postgres:
